package com.opengamma.strata.product.fxopt;

import com.opengamma.strata.basics.ReferenceData;
import com.opengamma.strata.basics.currency.AdjustablePayment;
import com.opengamma.strata.basics.currency.CurrencyPair;
import com.opengamma.strata.product.PortfolioItemInfo;
import com.opengamma.strata.product.PortfolioItemSummary;
import com.opengamma.strata.product.ProductType;
import com.opengamma.strata.product.ResolvableTrade;
import com.opengamma.strata.product.TradeInfo;
import com.opengamma.strata.product.common.SummarizerUtils;
import com.opengamma.strata.product.fx.FxOptionTrade;
import org.joda.beans.Bean;
import org.joda.beans.ImmutableBean;
import org.joda.beans.JodaBeanUtils;
import org.joda.beans.MetaBean;
import org.joda.beans.MetaProperty;
import org.joda.beans.gen.BeanDefinition;
import org.joda.beans.gen.ImmutableDefaults;
import org.joda.beans.gen.PropertyDefinition;
import org.joda.beans.impl.direct.DirectFieldsBeanBuilder;
import org.joda.beans.impl.direct.DirectMetaBean;
import org.joda.beans.impl.direct.DirectMetaProperty;
import org.joda.beans.impl.direct.DirectMetaPropertyMap;

import java.io.Serializable;
import java.util.Map;
import java.util.NoSuchElementException;

@BeanDefinition
public final class FxDigitalOptionTrade
    implements FxOptionTrade, ResolvableTrade<ResolvedFxDigitalOptionTrade>, ImmutableBean, Serializable {

  /**
   * The additional trade information, defaulted to an empty instance.
   * <p>
   * This allows additional information to be attached to the trade.
   */
  @PropertyDefinition(validate = "notNull", overrideGet = true)
  private final TradeInfo info;

  @PropertyDefinition(validate = "notNull", overrideGet = true)
  private final FxDigitalOption product;

  /**
   * The premium of the FX option.
   * <p>
   * The premium sign should be compatible with the product Long/Short flag.
   * This means that the premium is negative for long and positive for short.
   */
  @PropertyDefinition(validate = "notNull")
  private final AdjustablePayment premium;

  //-------------------------------------------------------------------------
  @ImmutableDefaults
  private static void applyDefaults(Builder builder) {
    builder.info = TradeInfo.empty();
  }

  //-------------------------------------------------------------------------
  @Override
  public FxDigitalOptionTrade withInfo(final PortfolioItemInfo info) {
    return new FxDigitalOptionTrade(TradeInfo.from(info), this.product, this.premium);
  }

  //-------------------------------------------------------------------------
  @Override
  public PortfolioItemSummary summarize() {
    // Long Barrier Pay USD 1mm Premium USD 100k @ GBP/USD 1.32 : 21Jan18
    final StringBuilder buf = new StringBuilder(96);
    buf.append(" Barrier ");
    buf.append(this.product.getBarrierType().toString());
    buf.append(" @ ");
    buf.append(this.product.getIndex());
    buf.append(" ");
    buf.append(this.product.getStrikePrice());
    buf.append(" Premium ");
    buf.append(SummarizerUtils.amount(this.premium.getValue().mapAmount(Math::abs)));
    buf.append(" : ");
    buf.append(SummarizerUtils.date(this.product.getExpiryDate()));
    final CurrencyPair currencyPair = this.product.getCurrencyPair();
    return SummarizerUtils.summary(
        this, ProductType.FX_DIGITAL_OPTION, buf.toString(), currencyPair.getBase(), currencyPair.getCounter());
  }

  @Override
  public ResolvedFxDigitalOptionTrade resolve(final ReferenceData refData) {
    return ResolvedFxDigitalOptionTrade.builder()
        .info(this.info)
        .premium(this.premium.resolve(refData))
        .product(this.product.resolve(refData))
        .build();
  }

  //------------------------- AUTOGENERATED START -------------------------
  /**
   * The meta-bean for {@code FxDigitalOptionTrade}.
   * @return the meta-bean, not null
   */
  public static FxDigitalOptionTrade.Meta meta() {
    return FxDigitalOptionTrade.Meta.INSTANCE;
  }

  static {
    MetaBean.register(FxDigitalOptionTrade.Meta.INSTANCE);
  }

  /**
   * The serialization version id.
   */
  private static final long serialVersionUID = 1L;

  /**
   * Returns a builder used to create an instance of the bean.
   * @return the builder, not null
   */
  public static FxDigitalOptionTrade.Builder builder() {
    return new FxDigitalOptionTrade.Builder();
  }

  private FxDigitalOptionTrade(
      TradeInfo info,
      FxDigitalOption product,
      AdjustablePayment premium) {
    JodaBeanUtils.notNull(info, "info");
    JodaBeanUtils.notNull(product, "product");
    JodaBeanUtils.notNull(premium, "premium");
    this.info = info;
    this.product = product;
    this.premium = premium;
  }

  @Override
  public FxDigitalOptionTrade.Meta metaBean() {
    return FxDigitalOptionTrade.Meta.INSTANCE;
  }

  //-----------------------------------------------------------------------
  /**
   * Gets the additional trade information, defaulted to an empty instance.
   * <p>
   * This allows additional information to be attached to the trade.
   * @return the value of the property, not null
   */
  @Override
  public TradeInfo getInfo() {
    return this.info;
  }

  //-----------------------------------------------------------------------
  /**
   * Gets the product.
   * @return the value of the property, not null
   */
  @Override
  public FxDigitalOption getProduct() {
    return this.product;
  }

  //-----------------------------------------------------------------------
  /**
   * Gets the premium of the FX option.
   * <p>
   * The premium sign should be compatible with the product Long/Short flag.
   * This means that the premium is negative for long and positive for short.
   * @return the value of the property, not null
   */
  public AdjustablePayment getPremium() {
    return this.premium;
  }

  //-----------------------------------------------------------------------
  /**
   * Returns a builder that allows this bean to be mutated.
   * @return the mutable builder, not null
   */
  public Builder toBuilder() {
    return new Builder(this);
  }

  @Override
  public boolean equals(Object obj) {
    if (obj == this) {
      return true;
    }
    if (obj != null && obj.getClass() == this.getClass()) {
      FxDigitalOptionTrade other = (FxDigitalOptionTrade) obj;
      return JodaBeanUtils.equal(this.info, other.info) &&
          JodaBeanUtils.equal(this.product, other.product) &&
          JodaBeanUtils.equal(this.premium, other.premium);
    }
    return false;
  }

  @Override
  public int hashCode() {
    int hash = getClass().hashCode();
    hash = hash * 31 + JodaBeanUtils.hashCode(this.info);
    hash = hash * 31 + JodaBeanUtils.hashCode(this.product);
    hash = hash * 31 + JodaBeanUtils.hashCode(this.premium);
    return hash;
  }

  @Override
  public String toString() {
    StringBuilder buf = new StringBuilder(128);
    buf.append("FxDigitalOptionTrade{");
    buf.append("info").append('=').append(JodaBeanUtils.toString(this.info)).append(',').append(' ');
    buf.append("product").append('=').append(JodaBeanUtils.toString(this.product)).append(',').append(' ');
    buf.append("premium").append('=').append(JodaBeanUtils.toString(this.premium));
    buf.append('}');
    return buf.toString();
  }

  //-----------------------------------------------------------------------
  /**
   * The meta-bean for {@code FxDigitalOptionTrade}.
   */
  public static final class Meta extends DirectMetaBean {
    /**
     * The singleton instance of the meta-bean.
     */
    static final Meta INSTANCE = new Meta();

    /**
     * The meta-property for the {@code info} property.
     */
    private final MetaProperty<TradeInfo> info = DirectMetaProperty.ofImmutable(
        this, "info", FxDigitalOptionTrade.class, TradeInfo.class);
    /**
     * The meta-property for the {@code product} property.
     */
    private final MetaProperty<FxDigitalOption> product = DirectMetaProperty.ofImmutable(
        this, "product", FxDigitalOptionTrade.class, FxDigitalOption.class);
    /**
     * The meta-property for the {@code premium} property.
     */
    private final MetaProperty<AdjustablePayment> premium = DirectMetaProperty.ofImmutable(
        this, "premium", FxDigitalOptionTrade.class, AdjustablePayment.class);
    /**
     * The meta-properties.
     */
    private final Map<String, MetaProperty<?>> metaPropertyMap$ = new DirectMetaPropertyMap(
        this, null,
        "info",
        "product",
        "premium");

    /**
     * Restricted constructor.
     */
    private Meta() {
    }

    @Override
    protected MetaProperty<?> metaPropertyGet(String propertyName) {
      switch (propertyName.hashCode()) {
        case 3237038:  // info
          return this.info;
        case -309474065:  // product
          return this.product;
        case -318452137:  // premium
          return this.premium;
      }
      return super.metaPropertyGet(propertyName);
    }

    @Override
    public FxDigitalOptionTrade.Builder builder() {
      return new FxDigitalOptionTrade.Builder();
    }

    @Override
    public Class<? extends FxDigitalOptionTrade> beanType() {
      return FxDigitalOptionTrade.class;
    }

    @Override
    public Map<String, MetaProperty<?>> metaPropertyMap() {
      return this.metaPropertyMap$;
    }

    //-----------------------------------------------------------------------
    /**
     * The meta-property for the {@code info} property.
     * @return the meta-property, not null
     */
    public MetaProperty<TradeInfo> info() {
      return this.info;
    }

    /**
     * The meta-property for the {@code product} property.
     * @return the meta-property, not null
     */
    public MetaProperty<FxDigitalOption> product() {
      return this.product;
    }

    /**
     * The meta-property for the {@code premium} property.
     * @return the meta-property, not null
     */
    public MetaProperty<AdjustablePayment> premium() {
      return this.premium;
    }

    //-----------------------------------------------------------------------
    @Override
    protected Object propertyGet(Bean bean, String propertyName, boolean quiet) {
      switch (propertyName.hashCode()) {
        case 3237038:  // info
          return ((FxDigitalOptionTrade) bean).getInfo();
        case -309474065:  // product
          return ((FxDigitalOptionTrade) bean).getProduct();
        case -318452137:  // premium
          return ((FxDigitalOptionTrade) bean).getPremium();
      }
      return super.propertyGet(bean, propertyName, quiet);
    }

    @Override
    protected void propertySet(Bean bean, String propertyName, Object newValue, boolean quiet) {
      metaProperty(propertyName);
      if (quiet) {
        return;
      }
      throw new UnsupportedOperationException("Property cannot be written: " + propertyName);
    }

  }

  //-----------------------------------------------------------------------
  /**
   * The bean-builder for {@code FxDigitalOptionTrade}.
   */
  public static final class Builder extends DirectFieldsBeanBuilder<FxDigitalOptionTrade> {

    private TradeInfo info;
    private FxDigitalOption product;
    private AdjustablePayment premium;

    /**
     * Restricted constructor.
     */
    private Builder() {
      applyDefaults(this);
    }

    /**
     * Restricted copy constructor.
     * @param beanToCopy  the bean to copy from, not null
     */
    private Builder(FxDigitalOptionTrade beanToCopy) {
      this.info = beanToCopy.getInfo();
      this.product = beanToCopy.getProduct();
      this.premium = beanToCopy.getPremium();
    }

    //-----------------------------------------------------------------------
    @Override
    public Object get(String propertyName) {
      switch (propertyName.hashCode()) {
        case 3237038:  // info
          return this.info;
        case -309474065:  // product
          return this.product;
        case -318452137:  // premium
          return this.premium;
        default:
          throw new NoSuchElementException("Unknown property: " + propertyName);
      }
    }

    @Override
    public Builder set(String propertyName, Object newValue) {
      switch (propertyName.hashCode()) {
        case 3237038:  // info
          this.info = (TradeInfo) newValue;
          break;
        case -309474065:  // product
          this.product = (FxDigitalOption) newValue;
          break;
        case -318452137:  // premium
          this.premium = (AdjustablePayment) newValue;
          break;
        default:
          throw new NoSuchElementException("Unknown property: " + propertyName);
      }
      return this;
    }

    @Override
    public Builder set(MetaProperty<?> property, Object value) {
      super.set(property, value);
      return this;
    }

    @Override
    public FxDigitalOptionTrade build() {
      return new FxDigitalOptionTrade(
          this.info,
          this.product,
          this.premium);
    }

    //-----------------------------------------------------------------------
    /**
     * Sets the additional trade information, defaulted to an empty instance.
     * <p>
     * This allows additional information to be attached to the trade.
     * @param info  the new value, not null
     * @return this, for chaining, not null
     */
    public Builder info(TradeInfo info) {
      JodaBeanUtils.notNull(info, "info");
      this.info = info;
      return this;
    }

    /**
     * Sets the product.
     * @param product  the new value, not null
     * @return this, for chaining, not null
     */
    public Builder product(FxDigitalOption product) {
      JodaBeanUtils.notNull(product, "product");
      this.product = product;
      return this;
    }

    /**
     * Sets the premium of the FX option.
     * <p>
     * The premium sign should be compatible with the product Long/Short flag.
     * This means that the premium is negative for long and positive for short.
     * @param premium  the new value, not null
     * @return this, for chaining, not null
     */
    public Builder premium(AdjustablePayment premium) {
      JodaBeanUtils.notNull(premium, "premium");
      this.premium = premium;
      return this;
    }

    //-----------------------------------------------------------------------
    @Override
    public String toString() {
      StringBuilder buf = new StringBuilder(128);
      buf.append("FxDigitalOptionTrade.Builder{");
      buf.append("info").append('=').append(JodaBeanUtils.toString(this.info)).append(',').append(' ');
      buf.append("product").append('=').append(JodaBeanUtils.toString(this.product)).append(',').append(' ');
      buf.append("premium").append('=').append(JodaBeanUtils.toString(this.premium));
      buf.append('}');
      return buf.toString();
    }

  }

  //-------------------------- AUTOGENERATED END --------------------------
}
